services:
  db:
    image: pgvector/pgvector:pg17
    container_name: quizlm_pg

    restart: unless-stopped

    env_file:
      - ./.env

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /db

    volumes:
      - postgres:/db

    ports:
      - "5432:5432"

    networks:
      - shared

volumes:
  postgres:

networks:
  shared: