// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import { config as loadEnv } from "dotenv";
import { defineConfig } from "prisma/config";

// Load environment variables from root .env file

let env = process.env;
if (!env.DB_URL && (!env.DB_USER || !env.DB_HOST || !env.DB_PORT || !env.DB_NAME)) {
  console.warn('loading env manually');
  loadEnv({ path: process.cwd() + "/../../.env" });
  env = process.env;
  if (!env.DB_URL && (!env.DB_USER || !env.DB_HOST || !env.DB_PORT || !env.DB_NAME)) {
    throw new Error("Database configuration is missing. Please set DB_URL or DB_USER, DB_HOST, DB_PORT, and DB_NAME in the environment variables.");
  }
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  typedSql: {
    path: "prisma/sql",
  },
  datasource: {
    // url: env("DATABASE_URL"),
    url: env.DB_URL || `postgresql://${env.DB_USER}:${encodeURIComponent(env.DB_PASSWORD!)}@${env.DB_HOST}:${env.DB_PORT}/${env.DB_NAME}`,
  },
});
